export type TFullAssignmentMatch = {
  match: number,
    red1: number,
    red1Scout: string, 
    red2: number,
    red2Scout: string, 
    red3: number,
    red3Scout: string, 
    blue1: number,
    blue1Scout: string, 
    blue2: number,
    blue2Scout: string, 
    blue3: number,
    blue3Scout: string,
}